### PR TITLE
Try to port to python3

### PR DESCRIPTION
**Pull request by titilambert**
Hello,

Python 2 will not be supported in 2020, so I'm trying to port this lib to python 3.x
I think I'm close to get it, but I'm still not able to fix the `test_save` test.

Are you interested by this PR ?
If yes, could you help me to find where is the issue for the `test_save` test ?

Thanks !

PS: I used `2to3` + some manual changes to get this.

### CODE REVIEW

**Comment by def-** [comment]
Hi. That sounds good to me. Note that we don't use this anymore in DDNet directly, but maybe others are still using it. We use https://github.com/heinrich5991/libtw2 instead to create the map-properties.

**Comment by def-** [comment]
What's wrong with test_save?

**Comment by ChillerDragon** [comment]
@def- nice that you care about others c:
Indeed we have some plans with tml for DDNet++

libtw2 is so confusing :c

**Comment by def-** [comment]
> libtw2 is so confusing

But infinitely more performant.

**Comment by timakro** [comment]
I made some DDRace specific changes and ported the library to Python 3 in my fork. Though I might have broken saving maps (I don't know if that ever worked for anything but vanilla maps, really). We at Unique use it to analyze race maps before we release them.

https://github.com/timakro/tml/commits/master

**Comment by def-** [comment]
Sounds like we should remove this repo then and link to yours instead.

**Comment by titilambert** [comment]
@timakro I have the same issue, save map seems broken ...
@timakro It seems that your fork have a lot missing commit compared to the DDnet one.
Do you think there are some missing features/fixes ?

**Comment by timakro** [comment]
I believe my version has the fixes from east, I remember taking a look at them. It also supports DDrace layers. I'm not sure if something else is missing.

**Comment by titilambert** [comment]
@timakro I have a patch to generate png image from a map file. Are you interested in this kind of patch ?

**Comment by timakro** [comment]
I would merge a PR if you implement it.

**Comment by titilambert** [comment]
@timakro PR created here: https://github.com/timakro/tml/pull/1
I'm closing this one.

**Pull request closed without merging**
